### PR TITLE
Define a default api.accessLog value.

### PR DESCRIPTION
**Pull request by sevko**
```
config/(defaults, expected-deep).json
	-Add a default value for the pelias/api configuration property
	introduced in https://github.com/pelias/api/pull/123 .
```

fixes pelias/api#8

### CODE REVIEW

**Comment by missinglink** [comment]
Is this going to enable api access logs by default in dev?

**Comment by sevko** [comment]
Yep, I think that's desirable.

**Comment by missinglink** [comment]
:+1:

**Comment by dianashk** [comment]
:+1:

**Pull request merged**
