### PR TITLE
Remove default value for `imports.whosonfirst.importVenues`

### PR DESCRIPTION
**Pull request by Joxit**
This is now a deprecated options.

related: pelias/whosonfirst#487

### CODE REVIEW

**Comment by missinglink** [comment]
before I hit merge, should we consider versioning this as a major since it's not backwards compatible?

**Comment by orangejulius** [comment]
I think its fine to have this as a non-breaking change, since it's only used elsewhere in Pelias.

However we should make sure any code that references these config variables are either able to handle empty values, or removed, _before_ we merge.

**Comment by orangejulius** [comment]
Looks like https://github.com/pelias/whosonfirst/pull/487 removed all use of `importVenues`, so this is good to merge.

**Comment by orangejulius** [comment]
Connects https://github.com/pelias/whosonfirst/issues/94

**Pull request merged**
