### PR TITLE
Remove deprecated index_concurrency parameter

### PR DESCRIPTION
**Pull request by fifthestateinc**

### CODE REVIEW

**Comment by fifthestateinc** [comment]
Oops, meant to merge it into my master first, but apparently that PR button goes all the way upstream. Not gonna be making any other changes to this branch though, so this is fine.

Addresses this: https://github.com/pelias/config/issues/44

**Comment by fifthestateinc** [comment]
Please wait on this PR until tests pass in the schema repo. This causes tests in schema to fail.

**Comment by fifthestateinc** [comment]
Alright, you may want to review this in tandem with https://github.com/pelias/schema/pull/195

**Comment by orangejulius** [comment]
Thanks for taking a look at this! We'll be working our way through all your PRs :)

**Pull request merged**
