### PR TITLE
Relative path to config file doesn't work #6

### PR DESCRIPTION
**Pull request by dianashk**
Added path.resolve for PELIAS_CONFIG env variable value.

### CODE REVIEW

**Comment by missinglink** [comment]
LGTM, would best best to add an accompanying testcase to avoid me breaking your code in future releases ;)

Something like the code below would be great:

```bash
diff --git a/test/generate.js b/test/generate.js
index c853656..81f417e 100644
--- a/test/generate.js
+++ b/test/generate.js
@@ -5,6 +5,37 @@ var path = require('path'),
 
 module.exports.generate = {};
 
+module.exports.generate.paths = function(test, common) {
+
+  var expected = require('../config/expected-deep.json');
+
+  test('absolute paths supported for ENV var', function(t) {
+
+    // set the absolute PELIAS_CONFIG env var
+    process.env['PELIAS_CONFIG'] = path.resolve( __dirname + '/../config/env.json' );
+
+    var c = config.generate();
+    t.deepEqual(c.export(), expected, 'loaded absolute file path');
+    t.end();
+
+    // unset the PELIAS_CONFIG env var
+    delete process.env['PELIAS_CONFIG'];
+  });
+
+  test('relative paths supported for ENV var', function(t) {
+
+    // set the relative PELIAS_CONFIG env var
+    process.env['PELIAS_CONFIG'] = './config/env.json';
+
+    var c = config.generate();
+    t.deepEqual(c.export(), expected, 'loaded relative file path');
+    t.end();
+
+    // unset the PELIAS_CONFIG env var
+    delete process.env['PELIAS_CONFIG'];
+  });
+};
+
```

**Comment by missinglink** [comment]
Can you also please pull master in to your fork, I fixed a test and it's now 1 commit out.

**Comment by dianashk** [comment]
:# I thought about the test as I was committing. Will add it and pull master first thing today.

**Comment by missinglink** [comment]
cool cool, catch you in a bit if I can stay awake long enough!

**Comment by dianashk** [comment]
done

**Pull request merged**
