### PR TITLE
fix(esclient): default esclient.apiVersion to 7.x

### PR DESCRIPTION
**Pull request by missinglink**
default `esclient.apiVersion` to 7.x

### CODE REVIEW

**Comment by missinglink** [comment]
cc @orangejulius are we good to pull the trigger on this now the dust has settled?

**Comment by orangejulius** [comment]
Interesting. I'm trying to wrap my head around what it means for the `apiVersion` to be `7.X` instead of `7.6`.

The `elasticsearch-js` docs aren't very clear, do you have any idea?

**Comment by missinglink** [comment]
My understanding is that `7.x` is equivalent for `7.latest`, unfortunately there is no `6.x` because ES 🤷‍♂

**Comment by missinglink** [comment]
Agreed this is probably not ideal but the [minor version breaking change](https://github.com/elastic/elasticsearch-js-legacy/issues/28) has forced our hand somewhat to act quickly to avoid widespread errors and bug reports.

Let's merge that and see what happens with ES, maybe we have better luck [than last time](https://github.com/elastic/elasticsearch/issues/49599) 🤷‍♂

**Pull request merged**
